language: c
compiler:
- gcc
os:
- linux
- osx
addons:
  apt:
    packages:
    - doxygen

before_install:
- openssl aes-256-cbc -K $encrypted_75641af13479_key -iv $encrypted_75641af13479_iv
  -in scripts/deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen; fi

script: make && make test
deploy:
  provider: script
  script: ruby scripts/generate_docs.rb
  on:
    branch: master
